[workspace]
resolver = "2"
members = ["crates/engine", "crates/app", "crates/plugins", "crates/host", "crates/stock", "crates/stock-ui", "crates/launcher", "crates/stretch"]

[workspace.package]
version = "0.5.0"

[profile.release]
lto = true
strip = true
opt-level = 3

[profile.dev.package.loupe-engine]
opt-level = 3

[profile.dev.package.loupe-stock]
opt-level = 3

[patch.crates-io]
iced_graphics = { path = "vendor/iced_graphics" }
