[package]
name = "loupe"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
loupe-engine = { path = "../engine" }
loupe-plugins = { path = "../plugins" }
loupe-stock = { path = "../stock" }
loupe-stock-ui = { path = "../stock-ui" }
iced = { version = "0.13", features = ["tokio", "canvas", "advanced", "image"] }
rfd = "0.14"
iced_runtime = "0.13"

[build-dependencies]
winresource = "0.1"
